# Generated by Django 5.0.6 on 2024-06-12 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_order_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='summary',
        ),
    ]
